name: rezappid
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  go_router: ^13.0.1
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/mlbb.jpeg
    - assets/images/ff.png
    - assets/images/pubg.png

