// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-OkZ-VKdOObwDYR_EbU_z2nzRkTWgcA8',
    appId: '1:873612404237:web:0b93d6db15125b11859744',
    messagingSenderId: '873612404237',
    projectId: 'betarezv1',
    authDomain: 'betarezv1.firebaseapp.com',
    storageBucket: 'betarezv1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-0ciQ0XT45AAujYJyMP0u1AW_2LiyvBM',
    appId: '1:873612404237:android:9c2f1ca1eb43d969859744',
    messagingSenderId: '873612404237',
    projectId: 'betarezv1',
    storageBucket: 'betarezv1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATZRPsNp9Vzo3Aqs0PQKNTDd-6YPAW9do',
    appId: '1:873612404237:ios:85d240806b89bd77859744',
    messagingSenderId: '873612404237',
    projectId: 'betarezv1',
    storageBucket: 'betarezv1.firebasestorage.app',
    iosBundleId: 'com.rezid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATZRPsNp9Vzo3Aqs0PQKNTDd-6YPAW9do',
    appId: '1:873612404237:ios:85d240806b89bd77859744',
    messagingSenderId: '873612404237',
    projectId: 'betarezv1',
    storageBucket: 'betarezv1.firebasestorage.app',
    iosBundleId: 'com.rezid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-OkZ-VKdOObwDYR_EbU_z2nzRkTWgcA8',
    appId: '1:873612404237:web:af18d67d7532fdb0859744',
    messagingSenderId: '873612404237',
    projectId: 'betarezv1',
    authDomain: 'betarezv1.firebaseapp.com',
    storageBucket: 'betarezv1.firebasestorage.app',
  );
}
